image:
  tag: latest
  pullPolicy: Always
env:
  TZ: Europe/Zurich
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: kanboard.bigli.io
        paths:
          - path: /
    tls:
      - hosts:
          - kanboard.bigli.io
        secretName: nzbget-tls
persistence:
  data:
    enabled: true
    storageClass: local-path-ssd
    accessMode: "ReadWriteOnce"
    size: '5Gi'
