apiVersion: v1
kind: Service
metadata:
  labels:
    app: joex
  name: joex
  namespace: docspell
spec:
  ports:
  - name: "7878"
    port: 7878
    protocol: TCP
    targetPort: 7878
  selector:
    app: joex
  type: ClusterIP
