---
# Source: ombi/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ombi-config
  labels:
    app.kubernetes.io/instance: ombi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ombi
    app.kubernetes.io/version: 4.16.12
    helm.sh/chart: ombi-11.4.0
  annotations:
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "local-path-ssd"
---
# Source: ombi/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: ombi
  labels:
    app.kubernetes.io/instance: ombi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ombi
    app.kubernetes.io/version: 4.16.12
    helm.sh/chart: ombi-11.4.0
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 3579
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: ombi
    app.kubernetes.io/instance: ombi
---
# Source: ombi/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ombi
  labels:
    app.kubernetes.io/instance: ombi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ombi
    app.kubernetes.io/version: 4.16.12
    helm.sh/chart: ombi-11.4.0
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ombi
      app.kubernetes.io/instance: ombi
  template:
    metadata:
      
      labels:
        app.kubernetes.io/name: ombi
        app.kubernetes.io/instance: ombi
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: ombi
          image: "ghcr.io/linuxserver/ombi:latest"
          imagePullPolicy: Always
          env:
            - name: "PGID"
              value: "1001"
            - name: "PUID"
              value: "1001"
            - name: "TZ"
              value: "Europe/Zurich"
          ports:
            - name: http
              containerPort: 3579
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: 3579
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3579
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 3579
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: ombi-config
---
# Source: ombi/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ombi
  labels:
    app.kubernetes.io/instance: ombi
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ombi
    app.kubernetes.io/version: 4.16.12
    helm.sh/chart: ombi-11.4.0
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - "ombi.bigli.io"
        - "plexrequests.bigli.io"
        - "requests.bigli.io"
      secretName: "ombi-tls"
  rules:
    - host: "ombi.bigli.io"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ombi
                port:
                  number: 3579
    - host: "plexrequests.bigli.io"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ombi
                port:
                  number: 3579
    - host: "requests.bigli.io"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: ombi
                port:
                  number: 3579
