image:
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - radarr.bigli.io
  tls:
    - hosts:
        - radarr.bigli.io
      secretName: radarr-tls
persistence:
  config:
    storageClass: local-path-ssd
  downloads:
    existingClaim: media-downloads
  movies:
    existingClaim: plex-media
    subPath: movies
