image:
  tag: latest
  pullPolicy: Always
env:
  PUID: '1001'
  PGID: '1001'
  TZ: Europe/Zurich
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: sonarr.bigli.io
        paths:
          - path: /
    tls:
      - hosts:
          - sonarr.bigli.io
        secretName: sonarr-tls
persistence:
  config:
    enabled: true
    storageClass: local-path-ssd
  downloads:
    enabled: true
    existingClaim: media-downloads
  tv:
    enabled: true
    existingClaim: plex-media
    subPath: tvshows
