image:
  tag: latest
  pullPolicy: Always
env:
  TZ: Europe/Zurich
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
      cert-manager.io/cluster-issuer: letsencrypt-prod
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - host: tautulli.bigli.io
        paths:
          - path: /
    tls:
      - hosts:
          - tautulli.bigli.io
        secretName: tautulli-tls
persistence:
  config:
    enabled: true
    storageClass: local-path-ssd
