---
# Source: tautulli/templates/common.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tautulli-config
  labels:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/version: v2.7.7
    helm.sh/chart: tautulli-11.3.2
  annotations:
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: "local-path-ssd"
---
# Source: tautulli/templates/common.yaml
apiVersion: v1
kind: Service
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/version: v2.7.7
    helm.sh/chart: tautulli-11.3.2
  annotations:
spec:
  type: ClusterIP
  ports:
  - port: 8181
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/instance: tautulli
---
# Source: tautulli/templates/common.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/version: v2.7.7
    helm.sh/chart: tautulli-11.3.2
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: tautulli
      app.kubernetes.io/instance: tautulli
  template:
    metadata:
      
      labels:
        app.kubernetes.io/name: tautulli
        app.kubernetes.io/instance: tautulli
    spec:
      
      serviceAccountName: default
      automountServiceAccountToken: true
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      containers:
        - name: tautulli
          image: "ghcr.io/k8s-at-home/tautulli:latest"
          imagePullPolicy: Always
          env:
            - name: "TZ"
              value: "Europe/Zurich"
          ports:
            - name: http
              containerPort: 8181
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8181
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: tautulli-config
---
# Source: tautulli/templates/common.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tautulli
  labels:
    app.kubernetes.io/instance: tautulli
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: tautulli
    app.kubernetes.io/version: v2.7.7
    helm.sh/chart: tautulli-11.3.2
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: traefik
spec:
  tls:
    - hosts:
        - "tautulli.bigli.io"
      secretName: "tautulli-tls"
  rules:
    - host: "tautulli.bigli.io"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: tautulli
                port:
                  number: 8181
