image:
  tag: latest
  pullPolicy: Always
global:
  storageClass: local-path-ssd
auth:
  existingSecret: paperless-postgresql
  database: paperless
  username: paperless

master:
  persistence:
    storageClass: local-path-ssd
replica:
  replicaCount: 0
