---
# Source: grafana/templates/tests/test-podsecuritypolicy.yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: graphs-grafana-test
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
spec:
  allowPrivilegeEscalation: true
  privileged: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
  fsGroup:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - projected
  - csi
  - secret
---
# Source: grafana/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
  name: graphs-grafana
  namespace: graphs
---
# Source: grafana/templates/tests/test-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
  name: graphs-grafana-test
  namespace: graphs
---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphs-grafana
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
data:
  allow-snippet-annotations: "false"
  plugins: grafana-clock-panel
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
---
# Source: grafana/templates/tests/test-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphs-grafana-test
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
data:
  run.sh: |-
    @test "Test Health" {
      url="http://graphs-grafana/api/health"

      code=$(wget --server-response --spider --timeout 10 --tries 1 ${url} 2>&1 | awk '/^  HTTP/{print $2}')
      [ "$code" == "200" ]
    }
---
# Source: grafana/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: graphs-grafana
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: local-path-ssd
---
# Source: grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graphs-grafana
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [graphs-grafana]
---
# Source: grafana/templates/tests/test-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graphs-grafana-test
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:      ['policy']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [graphs-grafana-test]
---
# Source: grafana/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: graphs-grafana
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: graphs-grafana
subjects:
- kind: ServiceAccount
  name: graphs-grafana
  namespace: graphs
---
# Source: grafana/templates/tests/test-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: graphs-grafana-test
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: graphs-grafana-test
subjects:
- kind: ServiceAccount
  name: graphs-grafana-test
  namespace: graphs
---
# Source: grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: graphs-grafana
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000

  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
---
# Source: grafana/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphs-grafana
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
      app.kubernetes.io/instance: graphs
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: grafana
        app.kubernetes.io/instance: graphs
      annotations:
        checksum/config: 315fc694237ef9148aa48e20ee95a0c4edf25f35c0561f9fe9599664904b39be
        checksum/dashboards-json-config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/sc-dashboard-provider-config: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
    spec:
      
      serviceAccountName: graphs-grafana
      automountServiceAccountToken: true
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
      initContainers:
        - name: init-chown-data
          image: "busybox:1.31.1"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "472:472", "/var/lib/grafana"]
          resources:
            {}
          volumeMounts:
            - name: storage
              mountPath: "/var/lib/grafana"
      enableServiceLinks: true
      containers:
        - name: grafana
          image: "grafana/grafana:8.5.21"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: "/etc/grafana/grafana.ini"
              subPath: grafana.ini
            - name: storage
              mountPath: "/var/lib/grafana"
          ports:
            - name: service
              containerPort: 80
              protocol: TCP
            - name: grafana
              containerPort: 3000
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-credentials
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-credentials
                  key: admin-password
            - name: GF_INSTALL_PLUGINS
              valueFrom:
                configMapKeyRef:
                  name: graphs-grafana
                  key: plugins
            - name: GF_PATHS_DATA
              value: /var/lib/grafana/
            - name: GF_PATHS_LOGS
              value: /var/log/grafana
            - name: GF_PATHS_PLUGINS
              value: /var/lib/grafana/plugins
            - name: GF_PATHS_PROVISIONING
              value: /etc/grafana/provisioning
            - name: "GF_AUTH_ANONYMOUS_ENABLED"
              value: "true"
            - name: "GF_SERVER_DOMAIN"
              value: "graphs.bigli.io"
            - name: "GF_SERVER_ROOT_URL"
              value: "https://graphs.bigli.io"
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
          resources:
            {}
      volumes:
        - name: config
          configMap:
            name: graphs-grafana
        - name: storage
          persistentVolumeClaim:
            claimName: graphs-grafana
---
# Source: grafana/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: graphs-grafana
  namespace: graphs
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
      - graphs.bigli.io
      secretName: graphs-bigli-io-cert
  rules:
    - host: graphs.bigli.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: graphs-grafana
                port:
                  number: 80
---
# Source: grafana/templates/tests/test.yaml
apiVersion: v1
kind: Pod
metadata:
  name: graphs-grafana-test
  labels:
    helm.sh/chart: grafana-6.29.11
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: graphs
    app.kubernetes.io/version: "8.5.3"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test-success
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
  namespace: graphs
spec:
  serviceAccountName: graphs-grafana-test
  containers:
    - name: graphs-test
      image: "bats/bats:1.9.0"
      imagePullPolicy: "IfNotPresent"
      command: ["/opt/bats/bin/bats", "-t", "/tests/run.sh"]
      volumeMounts:
        - mountPath: /tests
          name: tests
          readOnly: true
  volumes:
  - name: tests
    configMap:
      name: graphs-grafana-test
  restartPolicy: Never
