apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: graphs
spec:
  encryptedData:
    admin-password: AgBDSIL/c3a+WY0YF1iyrucw0oK8FFjMRWXCwatHe9KEe5nWFCIfQFMMitLk/YZReR8ARiZxieWPfjx/ovNBbm3a6/r1sKDEnLjER+i/qshlLLDr9J519AbKcuv45MCnGsxLPgHvt9N6i0EkNOxnqHfdqlDF/LD93z2UNsGHQNFBGx4VhyTBCZ8wsiqDdlNhebV4/psFAmiuyB1T6Qpzixeicqf6BW7ovqK62pkDBwUlke0S7Eu1fb+L5AtzutpYjOx2mX3mR4bmG+h+NGelvSGCW0jEhMtb6pTroE/cJ5CR4SL0b/Egd2q7gjnBJNlyFwaepqyStQy5O5vk5PsJf4+lkS91JF5f8PSlyaGA7o80wQf5BUwkPEXNQjqX9AEl1rJuP0eRyg3W6sFtnJmIE3UKJpPL6C8KQc7+e6Kn38uzmEsWROfMqZ+ZSDDKNN4TyY8o2el8GACjq+ZjmS48SNowlILBb/hmx45xjUIFqbH7uLrv3XgeiAvzIq+Z/2MS5sFcSCaN+z97O4mqvTzzt9onpptwBJlvjXByw9N7UFwWaAxrXa68wkzWqLyTyNYKppjqvxTMG0vloeI5q2tE+hxTwsiQm9Ro4QRSzJbXlhmeJE10WD2Cv9qcRdkXkKmqWm4qqrKLglqWxb83/q4AMzt16WsE4gdVqmsd6Cf+YU+UQXB1SScj6ki8HvSmGBGyAt/NqQDsFH9TqBzK7hdy9mRicVFVExN5WCYbSeGMIs2cEg==
    admin-user: AgCFbibOqs2Y48oL1ZDBNfIZ1sCsnCFEPpg38IfEBHBjhfMYQbh0HJm+jwcVW67YnQ+G1YzlUOqDL/XfQUxRwYn2nPlCSYpdmZceGzkSU5nsYHkGtrMx+CSaRbapuFMM9rdYkODmZgpewsoxVZ5qXLW6rU1q4DCqIllXGTU0HiloYWACrDXCnlwqVqnt/IGCxOA6lLVUMsnACglLNpFLkWKUNFt9le4NhoqDrMdlS9gKuCBUKx12iT22gSUn5iT11mvGsDQQV0Iin2F4aAnmy4DXywe8VE7o3mDmwcyk5OFLCaJUBsrV4q1QxIGtCYUucCJMbYBejaMOohDURFymO3Zk+efvf+hkzsJevyxG65vNeMUTRiwTf4K0VWC3O5AwV1qnxJNVn7cQ4VPSnY6uDpBqSI9QkKyL5x3uPlQS0Ojnybg4uNg1dD3I3F51TEWjkqROrXAZ6Z3FDgsy46l/wFMM9oVa8gcGB2zI/etdeU2QJayc1967wd2tnSMOlVXAacWBTome7V7hrbshBx2Vx+w4oLaxijuLNtIGYHXpNaGZ3UjeMJAkEukosEi0PThBkNWnKUiPuJxx/JLXdO0NQCq9eVDqhGM1/MVBJWXOyLqf7O+1PxqyhnoMzLRE5Hd2nTCkjj/9pUhIrJF2O8aU8ezsTMCs4SWDcSuiTyE+jBVeRPzX0mSRdpFgYR7c/pZFm1HQd20qlw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: graphs

