---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: object-backup
  namespace: k8up-cluster-backup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-backup-object-reader
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-backup-object-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-backup-object-reader
subjects:
  - kind: ServiceAccount
    name: object-backup
    namespace: k8up-cluster-backup
