apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: local-path-provisoner
    repoURL: https://github.com/TheBigLee/gitops-bigli-io.git
    targetRevision: HEAD
  destination:
    namespace: local-path-provisioner
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
     automated:
      prune: true
      selfHeal: true
