config:
  reporting_disabled: true
  auth_enabled: true
setDefaultUser:
  enabled: true
  user:
    existingSecret: influx-credentials

persistence:
  existingClaim: influxdb-data-influxdb-0
ingress:
  enabled: true
  tls: true
  secretName: influx-bigli-io-cert
  hostname: influx.bigli.io
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
