config:
  reporting_disabled: true

persistence:
  existingClaim: influxdb-data-influxdb-0
ingress:
  enabled: true
  tls: true
  secretName: influx-bigli-io-cert
  hostname: influx.bigli.io
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
