apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-data-influxdb-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path-ssd

